<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $getUrl = $storeManager->getStore()->getBaseUrl();
?>
<div class="actions">
    <?php $_order = $block->getOrder() ?>
    <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
        <a href="#" data-post='<?=
        /* @noEscape */ $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
            ->getPostData($block->getReorderUrl($_order))
        ?>' class="action order">
            <span><?= $block->escapeHtml(__('Reorder')) ?></span>
        </a>
    <?php endif ?>
    <?php
        foreach($_order->getInvoiceCollection() as $invoice){
            $invoiceIncrementID = $invoice->getIncrementId();
            $print_invoice_url = $getUrl.'pdf_invoice_frontend/invoice/pdfdownload/?invoice_id='.$invoice->getId();
        }
    ?>
    <?php 
    if(isset($invoiceIncrementID)): 
    ?>
        <a href="<?= $print_invoice_url ?>" class="action print">
            <span><?= $block->escapeHtml(__('Print Invoice')) ?></span>
        </a>
    <?php 
    endif;
    ?>
    <a href="<?= $block->escapeUrl($block->getPrintUrl($_order)) ?>"
       class="action print"
       target="_blank"
       rel="noopener">
        <span><?= $block->escapeHtml(__('Print Order')) ?></span>
    </a>
    <?= $block->getChildHtml() ?>
</div>
